name: "[DEV] Terraform"

on:
  pull_request:
    paths:
      - folder1/**
      - terraform/**

env:
  TF_INPUT: "0"
  TF_IN_AUTOMATION: "true"
  TF_WORKSPACE: "INT"

jobs:
  tf-validate:
    defaults:
      run:
        working-directory: terraform
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1

    - name: terraform-init
      id: terraform-init
      run: |
        terraform init \
          -no-color \
          -backend=false

    - name: terraform-fmt
      id: terraform-fmt
      run: |
        terraform fmt \
          -no-color \
          -recursive \
          -check

    - name: terraform-validate
      id: terraform-validate
      run: |
        terraform validate \
          -no-color

    - name: find-comment
      id: find-comment
      uses: peter-evans/find-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: "github-actions[bot]"
        body-includes: Terraform Validation

    - name: add-comment
      id: add-comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          # Terraform Validation

          <details>
          <summary>Expand init</summary>

          ```
          ${{ steps.terraform-init.outputs.stdout }}
          ```

          </details>

          <details>
          <summary>Expand fmt</summary>

          ```
          ${{ steps.terraform-fmt.outputs.stdout }}
          ```

          </details>

          <details>
          <summary>Expand validate</summary>

          ```
          ${{ steps.terraform-validate.outputs.stdout }}
          ```

          </details>
        edit-mode: replace

  tf-plan-INT:
    needs: [tf-validate]
    uses: ./.github/workflows/TPL_terraform_plan.yaml
    with:
      workspace: INT
      folder: terraform

  tf-plan-STG:
    needs: [tf-validate]
    uses: ./.github/workflows/TPL_terraform_plan.yaml
    with:
      workspace: STG
      folder: terraform

  tf-plan-PRD:
    needs: [tf-validate]
    uses: ./.github/workflows/TPL_terraform_plan.yaml
    with:
      workspace: PRD
      folder: terraform
