name: "[DEV] Terraform"

on:
  pull_request:
    paths:
      - folder1/**
      - terraform/**

env:
  TF_CLI_ARGS: "-chdir=terraform/"
  TF_INPUT: "0"
  TF_IN_AUTOMATION: "true"
  TF_WORKSPACE: "INT"

jobs:
  tf-validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1

    - name: terraform-init
      id: terraform-init
      run: |
        terraform init \
          -backend=false

    - name: terraform-fmt
      id: terraform-fmt
      run: |
        terraform fmt \
          -recursive \
          -check

    - name: terraform-validate
      id: terraform-validate
      run: |
        terraform validate

  tf-plan-INT:
    needs: [tf-validate]
    uses: ./.github/workflows/TPL_terraform_plan.yaml
    with:
      workspace: INT
      folder: terraform

  tf-plan-STG:
    needs: [tf-validate]
    uses: ./.github/workflows/TPL_terraform_plan.yaml
    with:
      workspace: STG
      folder: terraform

  tf-plan-PRD:
    needs: [tf-validate]
    uses: ./.github/workflows/TPL_terraform_plan.yaml
    with:
      workspace: PRD
      folder: terraform
