name: "STG - PRD"
on:
  push:
    tags:
      - v*.*.*
    paths:
      - 'folder1/**'
      - 'terraform/**'

jobs:
  tf-plan-stg:
    uses: ./.github/workflows/TPL_terraform_plan.yaml
    with:
      workspace: STG
      folder: terraform
      comment: false

  tf-deploy-stg:
    needs: [tf-plan-stg]
    uses: ./.github/workflows/TPL_terraform_deploy.yaml
    with:
      workspace: STG
      folder: terraform

  # This will be blocked by "environment reviewers" GitHub Action feature
  tf-plan-prd:
    needs: [tf-deploy-stg]
    uses: ./.github/workflows/TPL_terraform_plan.yaml
    with:
      workspace: PRD
      folder: terraform
      comment: false

  # This will be blocked by "environment reviewers" GitHub Action feature
  tf-deploy-prd:
    needs: [tf-plan-prd]
    uses: ./.github/workflows/TPL_terraform_deploy.yaml
    with:
      workspace: PRD
      folder: terraform
