name: "STG - PRD"
on:
  push:
    tags:
      - v*.*.*
    path:
      - folder1/**
      - terraform/**

jobs:
  tf-deploy-stg:
    uses: ./.github/workflows/TPL_terraform_deploy.yaml
    with:
      workspace: STG
      folder: terraform

  # This will be blocked by "environment reviewers" GitHub Action feature
  tf-deploy-prd:
    needs: [tf-deploy-stg]
    uses: ./.github/workflows/TPL_terraform_deploy.yaml
    with:
      workspace: PRD
      folder: terraform
