name: "[TPL] Terraform plan"
on:
  workflow_call:
    inputs:
      workspace:
        description: "Terraform workspace"
        default: "default"
        required: false
        type: string
      folder:
        description: "Terraform folder"
        required: true
        type: string

env:
  TF_CLI_ARGS: "-no-color"
  TF_INPUT: "0"
  TF_IN_AUTOMATION: "true"
  TF_WORKSPACE: "${{ inputs.workspace }}"

jobs:
  tf-plan:
    defaults:
      run:
        working-directory: ${{ inputs.folder }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1

    - name: terraform-init
      id: terraform-init
      run: |
        terraform init

    - name: terraform-plan
      id: terraform-plan
      run: |
        terraform plan \
          -lock=false \
          -compact-warnings \
          -var-file=workspace-${{ inputs.workspace }}.tfvars

    - name: find-comment
      id: find-comment
      uses: peter-evans/find-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: "github-actions[bot]"
        body-includes: Terraform Plan ${{ inputs.workspace }}

    - name: add-comment
      id: add-comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ## [Terraform Plan](${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }}/actions/runs/${{ env.GITHUB_RUN_ID }}) ${{ inputs.workspace }}

          <details>
          <summary>Expand plan</summary>

          ```
          ${{ steps.terraform-plan.outputs.stdout }}
          ```

          </details>
        edit-mode: replace
